### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by geekvc** [farrajota/dbcollection#15]
## I install used the source code
I installed successfully before I execute git pull commond
after I execute the git pull, error occured
```sh
$ sudo python setup.py install
[sudo] password for wangty:
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from dbcollection._version import VERSION
  File "/home/wangty/dbcollection/dbcollection/__init__.py", line 25, in <module>
    from .manager import load, download, process, add, remove, config_cache, query, info
  File "/home/wangty/dbcollection/dbcollection/manager.py", line 11, in <module>
    import dbcollection.datasets.funs as dataset
  File "/home/wangty/dbcollection/dbcollection/datasets/funs.py", line 8, in <module>
    from .dblist import datasets
  File "/home/wangty/dbcollection/dbcollection/datasets/dblist.py", line 14, in <module>
    from . import caltech, inria
  File "/home/wangty/dbcollection/dbcollection/datasets/caltech/__init__.py", line 3, in <module>
    from . import *
  File "/home/wangty/dbcollection/dbcollection/datasets/caltech/pedestrian/__init__.py", line 7, in <module>
    from .detection import Detection, Detection10x, Detection30x, DetectionNoSourceGrp, Detection10xNoSourceGrp, Detection30xNoSourceGrp
  File "/home/wangty/dbcollection/dbcollection/datasets/caltech/pedestrian/detection.py", line 16, in <module>
    from dbcollection.utils.caltech_pedestrian_extractor.converter import extract_data
ImportError: No module named caltech_pedestrian_extractor.converter
···
## conda install -c farrajota dbcollection
Python 2.7.13 |Anaconda 4.4.0 (64-bit)
```sh
$ conda install -c farrajota dbcollection
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - dbcollection -> patool -> python 3.5*
  - python 2.7*
Use "conda info <package>" to see the dependencies for each package.
```
## pip install dbcollection
successfully installed! 
```sh
$ pip install dbcollection
Requirement already satisfied: dbcollection in /home/wangty/dbcollection
Requirement already satisfied: h5py in /usr/lib/python2.7/dist-packages (from dbcollection)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from dbcollection)
Requirement already satisfied: patool in /usr/local/lib/python2.7/dist-packages (from dbcollection)
Requirement already satisfied: progressbar2 in /usr/local/lib/python2.7/dist-packages (from dbcollection)
Requirement already satisfied: scipy in /usr/local/lib/python2.7/dist-packages (from dbcollection)
Requirement already satisfied: xmltodict in /usr/local/lib/python2.7/dist-packages (from dbcollection)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from dbcollection)
Requirement already satisfied: Pillow in /usr/local/lib/python2.7/dist-packages (from dbcollection)
Requirement already satisfied: python-utils>=2.1.0 in /usr/local/lib/python2.7/dist-packages (from progressbar2->dbcollection)
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (from Pillow->dbcollection)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from python-utils>=2.1.0->progressbar2->dbcollection)
```

however, the demo failed.
```sh
$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbcollection as dbc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dbcollection/__init__.py", line 25, in <module>
    from .manager import load, download, process, add, remove, config_cache, query, info
  File "dbcollection/manager.py", line 11, in <module>
    import dbcollection.datasets.funs as dataset
  File "dbcollection/datasets/funs.py", line 8, in <module>
    from .dblist import datasets
  File "dbcollection/datasets/dblist.py", line 14, in <module>
    from . import caltech, inria
  File "dbcollection/datasets/caltech/__init__.py", line 3, in <module>
    from . import *
  File "dbcollection/datasets/caltech/pedestrian/__init__.py", line 7, in <module>
    from .detection import Detection, Detection10x, Detection30x, DetectionNoSourceGrp, Detection10xNoSourceGrp, Detection30xNoSourceGrp
  File "dbcollection/datasets/caltech/pedestrian/detection.py", line 16, in <module>
    from dbcollection.utils.caltech_pedestrian_extractor.converter import extract_data
ImportError: No module named caltech_pedestrian_extractor.converter
```

## I tested with the torch7
```sh
$ th

  ______             __   |  Torch7
 /_  __/__  ________/ /   |  Scientific computing for Lua.
  / / / _ \/ __/ __/ _ \  |  Type ? for help
 /_/  \___/_/  \__/_//_/  |  https://github.com/torch
                          |  http://torch.ch

th> dbc = require 'dbcollection.manager'
                                                                      [0.1948s]
th> dbc.load{name='pascal_voc_2007',task='detection_d'}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "dbcollection/__init__.py", line 25, in <module>
    from .manager import load, download, process, add, remove, config_cache, query, info
  File "dbcollection/manager.py", line 11, in <module>
    import dbcollection.datasets.funs as dataset
  File "dbcollection/datasets/funs.py", line 8, in <module>
    from .dblist import datasets
  File "dbcollection/datasets/dblist.py", line 14, in <module>
    from . import caltech, inria
  File "dbcollection/datasets/caltech/__init__.py", line 3, in <module>
    from . import *
  File "dbcollection/datasets/caltech/pedestrian/__init__.py", line 7, in <module>
    from .detection import Detection, Detection10x, Detection30x, DetectionNoSourceGrp, Detection10xNoSourceGrp, Detection30xNoSourceGrp
  File "dbcollection/datasets/caltech/pedestrian/detection.py", line 16, in <module>
    from dbcollection.utils.caltech_pedestrian_extractor.converter import extract_data
ImportError: No module named caltech_pedestrian_extractor.converter
/home/wangty/torch/install/share/lua/5.1/json/init.lua:40: attempt to index local 'f' (a nil value)
stack traceback:
        /home/wangty/torch/install/share/lua/5.1/json/init.lua:40: in function 'load'
        ...gty/torch/install/share/lua/5.1/dbcollection/manager.lua:129: in function 'load'
        [string "_RESULT={dbc.load{name='pascal_voc_2007',task..."]:1: in main chunk
        [C]: in function 'xpcall'
        /home/wangty/torch/install/share/lua/5.1/trepl/init.lua:661: in function 'repl'
        ...ngty/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
        [C]: at 0x00406620
                                                                      [0.4958s]
th>
```
Thank you in advance!

**Comment by farrajota** [comment]
First of all, sorry for all the trouble in installing this package. I need to fix Travis to correctly deploy the newest version of dbcollection to PyPi, so in the mean time my advice is to install it from source. 

To install it from source, you **must** use the `--recursive` flag to pull all the dependencies when doing a `git clone`:

```
git clone --recursive https://github.com/farrajota/dbcollection
```

If you don't do this, it will not retrieve the *caltech extractor* package and it will error on import. 
Then, install it by doing `cd dbcollection && python setup.py install`. 

Hopefully, I'll have PyPi/conda installation fixed in the following days, but for now you can install it from source and it should work properly. 

I'm finalizing some key steps of this package so bare with me if anything gets broken (hopefully it won't). If you have any more issues just let me know.

**Comment by geekvc** [comment]
Thank you for your prompt reply and excellent work.
I clone the repo recursively again, and install successfully.
and the mnist API demo goes well:
```sh
$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbcollection as dbc
>>> mnist = dbc.load('mnist')
Generating the dbcollection's package cache file on disk: /home/wangty/dbcollection.json
==> Download mnist data to disk...
==> Download complete.
==> Processing mnist metadata ...

Processing ::default:: task:

==> Storing metadata to file: /home/wangty/dbcollection/mnist/detection.h5

Saving set metadata: train

Saving set metadata: test
==> Processing complete.
```
however, the mnist.get("train", "data", 0) occurs error
```sh
>>> print('Dataset: ' + mnist.name)
Dataset: mnist
>>> print('Task: ' + mnist.task)
Task: default
>>> print('Data path: ' + mnist.data_dir)
Data path: /home/wangty/dbcollection/mnist/data
>>> print('Metadata cache path: ' + mnist.cache_path)
Metadata cache path: /home/wangty/dbcollection/mnist/detection.h5
>>> print('Sets: ', mnist.sets)
('Sets: ', [u'test', u'train'])
>>> import matplotlib.pyplot as plt
>>> plt.imshow(mnist.get("train", "data", 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dbcollection/loader.py", line 86, in get
    return self.file[field_path][idx]
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3403)
KeyError: "unable to open object (Symbol table: Can't open object)"
```

**Comment by farrajota** [comment]
I'm in the middle of some code refactoring, and the tutorials/examples are also being redone. Tomorrow I'll fix the jupyter notebook in `notebook/` with the new syntax. This notebook is a nice, quick and easy tutorial on how to use the API, so I'll keep you posted about the changes as they come.

 Nevertheless, I've updated the `README.md` with the correct label. For more information about what fields a dataset contains, just do this:

```python
import dbcollection as dbc
mnist = dbc.load('mnist')
print(mnist.list('train'))
```

The `.list()` method shows all available fields of a dataset split that can be retrieved from the API. For more information check the (temporary) documentation of the [Python dbcollection API](https://github.com/farrajota/dbcollection/blob/master/DOCUMENTATION.md).

**Comment by geekvc** [comment]
thank you very much!
now everything goes well, I will continue to pay attention to your work.

**Comment by Shadowwalker10** [comment]
where is the requirements.txt file
