### ISSUE TITLE
How to manage the custom dataset

### ISSUE THREAD

**Issue by geekvc** [farrajota/dbcollection#17]
I want to make a small dataset of coco, I just copied the first 5000 images in the coco validation dataset and named it with 5Kcoco. I want to manage the small dataset with dbcollection package.
I tried as follows:
```sh
>>> import dbcollection as dbc
>>> dbc.load('5Kcoco',data_dir='/data-4T/CommonDataSet/5Kcoco')
==> Download 5Kcoco data to disk...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dbcollection/manager.py", line 174, in load
    download(name, data_dir, True, verbose, is_test)
  File "dbcollection/manager.py", line 79, in download
    keywords = dataset.download(name, data_dir_, cache_save_path, extract_data, verbose)
  File "dbcollection/datasets/funs.py", line 124, in download
    dataset_loader = setup_dataset_constructor(name, data_dir, cache_dir, extract_data, verbose)
  File "dbcollection/datasets/funs.py", line 69, in setup_dataset_constructor
    constructor = fetch_dataset_constructor(name)
  File "dbcollection/datasets/funs.py", line 34, in fetch_dataset_constructor
    raise KeyError('Undefined dataset name: {}'.format(name))
KeyError: 'Undefined dataset name: 5Kcoco'
```
```sh
>>> dbc.add(name='5Kcoco',task='region_proposal',data_dir='/data-4T/CommonDataSet/5Kcoco',file_path='/home/wangty/dbcollection/5Kcoco')
>>> dbc.load('5Kcoco')
==> Processing 5Kcoco metadata ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dbcollection/manager.py", line 179, in load
    process(name, task, verbose, is_test)
  File "dbcollection/manager.py", line 126, in process
    cache_info = dataset.process(name, task, dset_paths['data_dir'], dset_paths['cache_dir'], verbose)
  File "dbcollection/datasets/funs.py", line 156, in process
    dataset_loader = setup_dataset_constructor(name, data_dir, cache_dir, False, verbose)
  File "dbcollection/datasets/funs.py", line 69, in setup_dataset_constructor
    constructor = fetch_dataset_constructor(name)
  File "dbcollection/datasets/funs.py", line 34, in fetch_dataset_constructor
    raise KeyError('Undefined dataset name: {}'.format(name))
KeyError: 'Undefined dataset name: 5Kcoco'
>>> dbc.process('5Kcoco')
==> Processing 5Kcoco metadata ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dbcollection/manager.py", line 126, in process
    cache_info = dataset.process(name, task, dset_paths['data_dir'], dset_paths['cache_dir'], verbose)
  File "dbcollection/datasets/funs.py", line 156, in process
    dataset_loader = setup_dataset_constructor(name, data_dir, cache_dir, False, verbose)
  File "dbcollection/datasets/funs.py", line 69, in setup_dataset_constructor
    constructor = fetch_dataset_constructor(name)
  File "dbcollection/datasets/funs.py", line 34, in fetch_dataset_constructor
    raise KeyError('Undefined dataset name: {}'.format(name))
KeyError: 'Undefined dataset name: 5Kcoco'
```
Is there anything wrong with my operation?

**Comment by farrajota** [comment]
Custom/Hand crafted datasets need to obey a few rules in order to work with the `dbcollection` API. These rules may be very simple depending on the type of data + annotations you have. This process will be simple to follow once the chapter in [creating a new dataset](http://dbcollection.readthedocs.io/en/latest/tutorial/create_new_dataset.html) is done.
Unfortunately, I haven't had the time to write the documentation about this, so it will be hard to explain it in detail how to craft a `hdf5` file for the small custom set you are trying to use. 

The easiest work around for your case is the following (and you won't need to copy any files whatsoever):

1. Load the `coco` dataset using `dbcollection`
```lua
dbc = require 'dbcollection'
coco = dbc.load{name='coco', task = 'detection_d'}
```

2. Lets define a range of files to define a subset of `coco` (lets use `n=5000`) to fetch data from, and lets fetch all annotations between 1 and `n` images. These indexes will be used to retrieve data of an image like bbox, category, filename, etc. For this, we'll use a special field of the `coco` `detection` task that groups all annotations by image: `list_object_ids_per_image` [see code](https://github.com/farrajota/dbcollection/blob/add_unit_tests/dbcollection/datasets/coco/detection.py#L550)
```lua
n = 5000
image_table = {}
for i=1, n do
    idx = coco.get(set_name, 'list_object_ids_per_image', i)  -- returns a tensor
    image_table[i] = idx.to_table()  -- convert tensor to table
end
```

3. Now that you have a table of indexes per image, you can simply cycle all your indexes and pull data using the `.object()` method:
```lua
im_id = 1  -- lets pull data for the image id == 1
obj_id = 1  -- lets pull the first annotation of the list
set_name = 'train'  -- lets fetch data from the train set
idx = image_table
data = coco:object(set_name, obj_id, true)  -- true converts indexes to data
-- do stuff with the data
```

This way lets you use only a subset of the entire dataset without much effort. You just need to set which images you want to use (it can be random indexes, it works just as fine) and retrieve the annotation data from the set. This method also allows you to mix multiple datasets by pulling information from any source you want and how you want it to be.

After this package reaches `0.2.0` I'll start adding more functionality like a method for creating custom datasets by requiring only a path as an input argument. Now I'm focused on finishing the documentation, adding unit tests and defining a starting base to improve and expand the library.  

If this is not a solution you want please let me know and I'll see how I can assist you with your issue.

**Comment by geekvc** [comment]
I am so sorry for my late reply, this weekend was occupied by some trifles. It is quite the solution I want, and I tried your advice as above:
1. Load the `coco` dataset using `dbcollection`, This load the whole `coco` dataset and create the `hdf5`  file, everything goes well.
```sh
th> dbc = require 'dbcollection'
                                                                      [0.1890s]
th> coco = dbc.load{name='coco', task = 'detection_d'}
==> Processing coco metadata ...

Processing ::detection_d:: task:

==> Storing metadata to file: /home/wangty/dbcollection/coco/detection_2015_d.h5

> Loading data files for the set: val
  > Loading annotation file: /home/wangty/dbcollection/coco/data/annotations/instances_val2014.json
  > Processing image annotations...
  > Processing category annotations...
  > Processing object annotations...
100% (291875 of 291875) |########################################################| Elapsed Time: 0:00:04 Time: 0:00:04

Saving set metadata: val
> Adding data to default group:
100% (40504 of 40504) |##########################################################| Elapsed Time: 0:00:02 Time: 0:00:02
> Processing coco lists:
100% (40504 of 40504) |##########################################################| Elapsed Time: 0:00:55 Time: 0:00:55
100% (291875 of 291875) |########################################################| Elapsed Time: 0:00:00 Time: 0:00:00
> Processing lists...

> Loading data files for the set: test
> Loading annotation file: /home/wangty/dbcollection/coco/data/annotations/image_info_test2014.json
> Processing image annotations...
> Processing category annotations...

Saving set metadata: test
> Adding data to default group:
100% (40775 of 40775) |##########################################################| Elapsed Time: 0:00:00 Time: 0:00:00
> Processing coco lists:
100% (40775 of 40775) |##########################################################| Elapsed Time: 0:00:50 Time: 0:00:50

> Loading data files for the set: train
  > Loading annotation file: /home/wangty/dbcollection/coco/data/annotations/instances_train2014.json
  > Processing image annotations...
  > Processing category annotations...
  > Processing object annotations...
100% (604907 of 604907) |########################################################| Elapsed Time: 0:00:08 Time: 0:00:08

Saving set metadata: train
> Adding data to default group:
100% (82783 of 82783) |##########################################################| Elapsed Time: 0:00:08 Time: 0:00:08
> Processing coco lists:
100% (82783 of 82783) |##########################################################| Elapsed Time: 0:04:29 Time: 0:04:29
100% (604907 of 604907) |########################################################| Elapsed Time: 0:00:01 Time: 0:00:01
> Processing lists...
==> Processing complete.
```
2. Fetch all annotations between 1 and 5000 images, I am confused about the `set_name` in `idx = coco.get(set_name, 'list_object_ids_per_image', i)`  and I tried as follows:
```sh
th> idx = coco.get(set_name, 'list_object_ids_per_image', 1)
...ngty/torch/install/share/lua/5.1/dbcollection/loader.lua:89: attempt to index local 'self' (a nil value)
stack traceback:
        ...ngty/torch/install/share/lua/5.1/dbcollection/loader.lua:89: in function 'get'
        [string "idx = coco.get(set_name, 'list_object_ids_per..."]:1: in main chunk
        [C]: in function 'xpcall'
        /home/wangty/torch/install/share/lua/5.1/trepl/init.lua:679: in function 'repl'
        ...ngty/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
        [C]: at 0x00406620
                                                                      [0.0008s]
th> coco.get('coco','list_object_ids_per_image', 1)
...ngty/torch/install/share/lua/5.1/dbcollection/loader.lua:90: attempt to index field 'file' (a nil value)
stack traceback:
        ...ngty/torch/install/share/lua/5.1/dbcollection/loader.lua:90: in function 'get'
        [string "_RESULT={coco.get('coco','list_object_ids_per..."]:1: in main chunk
        [C]: in function 'xpcall'
        /home/wangty/torch/install/share/lua/5.1/trepl/init.lua:661: in function 'repl'
        ...ngty/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
        [C]: at 0x00406620
th> idx = coco.get('5Kcoco', 'list_object_ids_per_image', 1)
...ngty/torch/install/share/lua/5.1/dbcollection/loader.lua:90: attempt to index field 'file' (a nil value)
stack traceback:
        ...ngty/torch/install/share/lua/5.1/dbcollection/loader.lua:90: in function 'get'
        [string "idx = coco.get('5Kcoco', 'list_object_ids_per..."]:1: in main chunk
        [C]: in function 'xpcall'
        /home/wangty/torch/install/share/lua/5.1/trepl/init.lua:679: in function 'repl'
        ...ngty/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
        [C]: at 0x00406620
th> idx = coco.get('train', 'list_object_ids_per_image', 1)
...ngty/torch/install/share/lua/5.1/dbcollection/loader.lua:90: attempt to index field 'file' (a nil value)
stack traceback:
        ...ngty/torch/install/share/lua/5.1/dbcollection/loader.lua:90: in function 'get'
        [string "idx = coco.get('train', 'list_object_ids_per_..."]:1: in main chunk
        [C]: in function 'xpcall'
        /home/wangty/torch/install/share/lua/5.1/trepl/init.lua:679: in function 'repl'
        ...ngty/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
        [C]: at 0x00406620
```

**Comment by farrajota** [comment]
Sorry, completely mixed the example code with the python and lua API calls. Let me redo the example code for the Lua/Torch7 API that works. (I'll do a train and validation split of the dataset so you can see how it works for more than one set split.). Also, I'm fixing some issues with the `coco` dataset, so I'll provide here a more complex solution than the simples one that is possible (I'll post this one also as soon as I get this issue sorted).

The following example code will load the `coco` dataset, fetch data for only the first `n=500` images and retrieves the image, bounding box location, category label 

## fetch data from the COCO *train* set

```lua
require 'torch'
require 'xlua'
dbc = require 'dbcollection'
ascii2str = dbc.utils.string_ascii.convert_ascii_to_str
unpad_list = dbc.utils.pad.unpad_list

-- load the coco dataset
coco = dbc.load{name='coco', task='detection_d'}

-- define the number of images to use from a set
n = 500
set_name = 'train'  -- change to 'val' to use the validation set instead

-- cycle all images and retrieve all annotation data
img_annotations = {}
for i=1, n do
    xlua.progress(i, n)
    -- get all annotation indexes for the 'ith' image
    annot_idx = unpad_list(coco:get(set_name, 'list_object_ids_per_image', i))[1]
    
    -- now that we have the indexes of all objects in the 'ith' image, we can fetch the data
    data = {}  -- store all annotation data in a table
    for j=1, #annot_idx do
         obj_idx = annot_idx[j] + 1 -- object index to fetch (since lua is 1-indexes we need to add +1)
         annotations_indexes =  coco:object(set_name, obj_idx)  -- returns the fields indexes for this image

         -- select the fields filename + category label + bounding box 
         filename = coco:get(set_name, 'image_filenames', annotations_indexes[1][1])
         filename = paths.concat(coco.data_dir, ascii2str(filename)[1])  -- builds the image filename wrt where its stored in disk
         label_name = ascii2str(coco:get(set_name, 'category', annotations_indexes[1][5]))[1]
         label_id = annotations_indexes[1][5]
         bbox = coco:get(set_name, 'boxes', annotations_indexes[1][7])[1]

         -- add these fields
         table.insert(data, {filename = filename, label=label_name, label_id=label_id, bbox= bbox})
    end

    table.insert(img_annotations, data)
end

-- Lets look at an image and display the image and the label + bounding box coordinates
-- WARNING: must run this using the qlua interpreter to visualize the image
require 'image'
id = 100  -- lets check the 100th image
iobj = 1  -- lets check the second object on the image
object_annotations = img_annotations[id][iobj]
filename = object_annotations.filename
label = object_annotations.label
bbox = object_annotations.bbox

-- load image
img = image.load(filename, 3, 'float')

-- plot image + bbox
if pcall(require, 'qt') then
    print(bbox)
    print(label)
    im = image.drawRect(img, bbox[1], bbox[2], bbox[3], bbox[4], {lineWidth = 5, color = {0, 255, 0}})
    im = image.drawText(im, label, bbox[1], bbox[2], {color = {255,0, 0}, size = 4})
    image.display{image=im, title=label}
else
    print('To visualize this image you must use the \'qlua\' interpreter')
end
```

I'll post another (simpler) example once I've fixed some issues with the coco dataset. For now this example should illustrate how to fetch a subset of data samples with the `coco` dataset.

**Comment by geekvc** [comment]
Thank you very much for your detailed description and I have already successful make my own subset of coco follow your script.

**Comment by geekvc** [comment]
The above script is quite useful for my work, and I fetch the first 5000 images in the front part my script. if the reslut `img_annotations` table can be saved as a `hdf5` file to the disk, and add it to the `dbcollection.json`, then we can use it more conveniently, such as load it as follows:
```sh
dbc = require 'dbcollection'
coco = dbc.load{name='coco5k', task = 'do_something'}
```

**Comment by farrajota** [comment]
Using a `hdf5` file in conjunction with the `dbcollection` API is a bit more complex than that. There is indeed an API method to add custom datasets + `hdf5` file to the list of available options to load: the [dbcollection.add()](https://github.com/dbcollection/dbcollection/blob/master/DOCUMENTATION.md#add). This command allows the user to specify the dataset name, task, data directory and the `hdf5` metadata file name+path. 

This `hdf5` metadata file has to be build in a certain way to work with the `.get()` and `.object()` API methods to fetch data. Also, there are caveats in the lua/torch `hdf5` module that requires the setup of this file to be done in a certain way regarding strings. If you are interested in learning more about how to setup your own dataset, you can check how other dataset examples are built like the [cifar10](https://github.com/dbcollection/dbcollection/tree/master/dbcollection/datasets/cifar/cifar10) or the [mnist](https://github.com/dbcollection/dbcollection/tree/master/dbcollection/datasets/mnist) datasets. 

> Warning: For now, you'll have to look at other examples in the `datasets/` directory while I write the tutorial on *how to build your own dataset* in the documentation.

### Workaround

Having said all this, I suspect that this is not what you are looking for at this moment. To save you some work, you can hack something like the following: **(Note: I've setup this w.r.t the Lua/Torch side of things)**

1. Create a function to fetch data for your train and validation sets (if you have split the data this way)
2. Use the `torch.save()` method to save the previous function into a file, like `torch.save(some_filename, load_coco5k_fun)`. This way, you can reuse the data loading function for your `coco5k` dataset in a simple and easy way. 

### Some considerations

This will not be as convenient as using the `dbcollection` API to store your custom dataset, but it will still use the API but in a more 'hacky' way. 

I hope to start tackling the documentation soon so stuff like adding or changing a dataset can be easy to understand, but for now if you have the courage to dive into the code then you are more brave than I am. (My advice is to stay away from it for now!)

**Comment by geekvc** [comment]
Through your detailed explanation, I believe direct using the fetch script to get my custom dataset and using `torch.save()` method to save the temporary file to disk is the most easiest way to solve the problem.
Thanks again!

**Comment by farrajota** [comment]
Due to some changes in `dbcollection` (Python + Lua/Torch7 APIs), the previous script won't work properly. You can use the following script to fetch data from the coco dataset as done before, but it should now work with the new changes.

### fetch data from the *coco* dataset

```lua
require 'torch'
require 'xlua'
dbc = require 'dbcollection'

-- load the coco dataset
dbloader = dbc.load('coco')


--------------------------------------------------------------------------------
-- Function to fetch data from the Coco dataset
--------------------------------------------------------------------------------

function fetch_data_coco(set_name, fileid)
    local utils = require 'dbcollection.utils'
    local ascii2str = utils.string_ascii.convert_ascii_to_str
    local unpad = utils.pad.unpad_list

    local objs_ids = unpad(dbloader:get(set_name, 'list_object_ids_per_image', fileid))
    if #objs_ids == 0 then
        return nil
    end

    local data = {}
    for _, id in ipairs(objs_ids) do
        local obj_id = dbloader:object(set_name, id+1):squeeze()  -- set id to 1-index
        local filename = paths.concat(dbloader.data_dir, ascii2str(dbloader:get(set_name, 'image_filenames', obj_id[1])))
        local bbox = dbloader:get(set_name, 'boxes', obj_id[7]):squeeze()
        local label = ascii2str(dbloader:get(set_name, 'category', obj_id[5]))
        local label_id = obj_id[5]
        table.insert(data, {filename = filename,
                            bbox = bbox,
                            label = label,
                            label_id = label_id})
    end
    return data
end


--------------------------------------------------------------------------------
-- Lets try fetching data from the 'train' and 'val' sets and display it
--------------------------------------------------------------------------------

-- Lets look at an image and display the image and the label + bounding box coordinates
-- WARNING: must run this using the qlua interpreter to visualize the image
require 'image'

train_data_sample = fetch_data_coco('train', 1)  -- fetch data from image 1
val_data_sample = fetch_data_coco('val', 150)  -- fetch data from image 150

max_objects_display = 2

-- load image
if pcall(require, 'qt') then
    -- show train data sample
    for k=1, math.min(max_objects_display, #train_data_sample) do
        print(('(train) Display object %d/%d'):format(k, #train_data_sample))
        data = train_data_sample[k]
        img = image.load(data.filename, 3, 'float')
        bbox = data.bbox
        label = data.label
        label_id = data.label_id
        im = image.drawRect(img, bbox[1], bbox[2], bbox[3], bbox[4], {lineWidth = 5, color = {0, 255, 0}})
        im = image.drawText(im, ('%s\nid=%d'):format(label, label_id), bbox[1], bbox[2], {color = {255,0, 0}, size = 3})
        image.display{image=im, title=label}
    end

    -- show val data sample
    for k=1, math.min(max_objects_display, #val_data_sample) do
        print(('(val) Display object %d/%d'):format(k, #val_data_sample))
        data = val_data_sample[k]
        img = image.load(data.filename, 3, 'float')
        bbox = data.bbox
        label = data.label
        label_id = data.label_id
        im = image.drawRect(img, bbox[1], bbox[2], bbox[3], bbox[4], {lineWidth = 5, color = {0, 255, 0}})
        im = image.drawText(im, ('%s\nid=%d'):format(label, label_id), bbox[1], bbox[2], {color = {255,0, 0}, size = 3})
        image.display{image=im, title=label}
    end
else
    print('To visualize this image you must use the \'qlua\' interpreter')
end
```
